# Generated by Django 3.1.3 on 2021-02-11 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k_admin', '0006_empreg_status'),
        ('k_telicaller', '0004_telefb'),
    ]

    operations = [
        migrations.CreateModel(
            name='fieldempfb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('fbmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k_admin.empreg')),
                ('telefb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k_telicaller.telefb')),
            ],
        ),
    ]
