# Generated by Django 3.1.3 on 2021-04-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_fieldemployee', '0002_instalmant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instalmant',
        ),
    ]
