# Generated by Django 3.1.3 on 2021-04-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_fieldemployee', '0004_instalmant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='instalmant',
        ),
    ]
