# Generated by Django 3.1.3 on 2021-04-24 15:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('k_admin', '0006_empreg_status'),
        ('k_employee', '0002_customer_currentamont'),
        ('k_fieldemployee', '0005_delete_instalmant'),
    ]

    operations = [
        migrations.CreateModel(
            name='instalmant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalmentstatus', models.CharField(max_length=50)),
                ('loneamount', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('currentdate', models.DateField(default=django.utils.timezone.now)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k_employee.customer')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k_admin.empreg')),
            ],
        ),
    ]
