# Generated by Django 3.1.3 on 2021-02-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('k_admin', '0005_delete_customer'),
        ('k_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teleFB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k_employee.customer')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='k_admin.login')),
            ],
        ),
    ]
