# Generated by Django 3.1.3 on 2021-02-11 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_telicaller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telefb',
            name='cust',
        ),
        migrations.RemoveField(
            model_name='telefb',
            name='login',
        ),
    ]
