# Generated by Django 3.1.3 on 2021-02-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k_telicaller', '0002_auto_20210211_1126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='teleFB',
        ),
    ]
