# Generated by Django 3.1.3 on 2021-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('adress', models.CharField(max_length=30)),
                ('mob', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=30)),
                ('bank', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=30)),
                ('acc_no', models.IntegerField(default=0)),
                ('loanduration', models.CharField(max_length=30)),
                ('loanapprove', models.DateField()),
                ('loanamount', models.IntegerField(default=0)),
                ('emi', models.IntegerField(default=0)),
            ],
        ),
    ]
