# Generated by Django 3.1.3 on 2021-04-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k_employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='currentamont',
            field=models.IntegerField(default=0),
        ),
    ]
